import os
import sys
from typing import Generator, Dict, Any, List, Optional
from openai import OpenAI

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding='utf-8')
        sys.stderr.reconfigure(encoding='utf-8')
    except Exception:
        pass

try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

DEFAULT_MODEL = "openrouter/free"

DEFAULT_SYSTEM_PROMPT = """You are a smart, interactive AI study planning assistant like ChatGPT.
Your role is to:
1. Understand the user's specific learning goal and background.
2. Break it into actionable, structured phases and milestones.
3. Formulate study plans with time estimates, active recall exercises, and practical projects.
4. Maintain full conversational context across follow-up questions, clarifying doubts, providing in-depth explanations, code snippets, or adjusting study schedules as requested."""

def get_client(api_key: Optional[str] = None) -> Optional[OpenAI]:
    """Retrieve an OpenAI client configured for OpenRouter."""
    key = api_key or os.getenv("OPENROUTER_API_KEY")
    if not key or not key.strip():
        return None
    return OpenAI(
        api_key=key.strip(),
        base_url="https://openrouter.ai/api/v1"
    )

def build_messages_context(
    goal: str,
    history: Optional[List[Dict[str, str]]] = None,
    system_instruction: Optional[str] = None
) -> List[Dict[str, str]]:
    """
    Constructs the genuine, complete context window for the AI model.
    Includes system instructions, prior conversation turns, and the latest user prompt.
    """
    messages: List[Dict[str, str]] = []

    # 1. System Prompt / Persona Instruction
    system_content = (system_instruction or "").strip() or DEFAULT_SYSTEM_PROMPT
    messages.append({"role": "system", "content": system_content})

    # 2. Prior Conversation History (Multi-Turn Context)
    if history:
        for msg in history:
            role = msg.get("role", "").strip()
            content = msg.get("content", "").strip()
            if role in ("user", "assistant", "system") and content:
                # If the last message in history is identical to the current goal, skip duplicating
                if role == "user" and content == goal.strip() and msg == history[-1]:
                    continue
                messages.append({"role": role, "content": content})

    # 3. Current User Query / Goal
    if goal and goal.strip():
        # Only append if not already the last item
        if not messages or messages[-1].get("content") != goal.strip():
            messages.append({"role": "user", "content": goal.strip()})

    return messages

def study_agent(
    goal: str,
    history: Optional[List[Dict[str, str]]] = None,
    api_key: Optional[str] = None,
    model: str = DEFAULT_MODEL,
    system_instruction: Optional[str] = None
) -> str:
    """
    Synchronous execution with full conversational context sent to OpenRouter.
    """
    client = get_client(api_key)
    if not client:
        return (
            "⚠️ **OpenRouter API Key Missing**\n\n"
            "To connect to the live AI model with actual context, please configure your OpenRouter API key.\n"
            "- Set `OPENROUTER_API_KEY=your_key` in a `.env` file or environment.\n"
            "- Or enter it in the web interface settings ⚙️.\n"
            "Get free API keys at: https://openrouter.ai/keys"
        )

    messages = build_messages_context(goal, history, system_instruction)

    try:
        response = client.chat.completions.create(
            model=model or DEFAULT_MODEL,
            messages=messages
        )
        return response.choices[0].message.content or "No response received from model."
    except Exception as e:
        err_str = str(e).lower()
        if ("404" in err_str or "unavailable for free" in err_str or "not found" in err_str) and (model != "openrouter/free"):
            try:
                response = client.chat.completions.create(
                    model="openrouter/free",
                    messages=messages
                )
                return f"> *[Notice: `{model}` was unavailable. Auto-routed to `openrouter/free`]*\n\n{response.choices[0].message.content}"
            except Exception as e2:
                return f"⚠️ **OpenRouter API Error:** {str(e2)}"
        return f"⚠️ **OpenRouter API Error:** {str(e)}"

def study_agent_stream(
    goal: str,
    history: Optional[List[Dict[str, str]]] = None,
    api_key: Optional[str] = None,
    model: str = DEFAULT_MODEL,
    system_instruction: Optional[str] = None
) -> Generator[Dict[str, Any], None, None]:
    """
    Real-time streaming directly from OpenRouter with actual conversation context.
    Yields chunks as generated by the LLM.
    """
    client = get_client(api_key)
    if not client:
        err_msg = (
            "⚠️ **OpenRouter API Key Required**\n\n"
            "The model requires an API key to process your prompt with actual conversation context.\n\n"
            "**How to add your key:**\n"
            "1. Click the **⚙️ Settings** icon in the UI and paste your key, OR\n"
            "2. Add `OPENROUTER_API_KEY=sk-or-v1-...` to your `.env` file.\n\n"
            "*Get free keys instantly at [openrouter.ai/keys](https://openrouter.ai/keys)*"
        )
        yield {
            "chunk": err_msg,
            "context_count": 0,
            "error": True,
            "done": True
        }
        return

    # Build the real messages array with full context
    messages = build_messages_context(goal, history, system_instruction)
    active_model = model or DEFAULT_MODEL

    try:
        response_stream = client.chat.completions.create(
            model=active_model,
            messages=messages,
            stream=True
        )
    except Exception as e:
        err_str = str(e).lower()
        if ("404" in err_str or "unavailable for free" in err_str or "not found" in err_str) and active_model != "openrouter/free":
            yield {
                "chunk": f"> *[Notice: `{active_model}` was unavailable for free. Automatically routed your query to `openrouter/free`]*\n\n",
                "context_count": len(messages),
                "done": False
            }
            try:
                response_stream = client.chat.completions.create(
                    model="openrouter/free",
                    messages=messages,
                    stream=True
                )
            except Exception as e2:
                yield {
                    "chunk": f"\n\n⚠️ **OpenRouter API Error:** {str(e2)}",
                    "context_count": len(messages),
                    "error": True,
                    "done": True
                }
                return
        else:
            yield {
                "chunk": f"\n\n⚠️ **OpenRouter API Error:** {str(e)}",
                "context_count": len(messages),
                "error": True,
                "done": True
            }
            return

    try:
        for chunk in response_stream:
            delta = chunk.choices[0].delta.content if chunk.choices and chunk.choices[0].delta else None
            if delta:
                yield {
                    "chunk": delta,
                    "context_count": len(messages),
                    "done": False
                }

        yield {
            "chunk": "",
            "context_count": len(messages),
            "done": True
        }

    except Exception as e:
        yield {
            "chunk": f"\n\n⚠️ **OpenRouter API Error:** {str(e)}",
            "context_count": len(messages),
            "error": True,
            "done": True
        }

# CLI Compatibility for terminal use
if __name__ == "__main__":
    print("=" * 60)
    print(" 📚 SMART STUDY PLANNER & CONTEXT AGENT (CLI Mode)")
    print("=" * 60)
    
    # Check for API key
    if not os.getenv("OPENROUTER_API_KEY"):
        print("Note: OPENROUTER_API_KEY environment variable is not set.")
        key_input = input("Enter your OpenRouter API key (or press Enter to skip): ").strip()
        if key_input:
            os.environ["OPENROUTER_API_KEY"] = key_input
            
    chat_history: List[Dict[str, str]] = []
    print("\nType your learning goal or question. Type 'exit' to quit.\n")
    
    while True:
        try:
            user_input = input("\nYou: ").strip()
            if not user_input or user_input.lower() in ("exit", "quit"):
                print("Goodbye!")
                break
                
            print("\nAI Thinking (with full context)...")
            reply = study_agent(user_input, history=chat_history)
            print(f"\nAI:\n{reply}\n")
            
            # Maintain multi-turn context
            chat_history.append({"role": "user", "content": user_input})
            chat_history.append({"role": "assistant", "content": reply})
            print(f"[{len(chat_history)} messages in context]")
            
        except (KeyboardInterrupt, EOFError):
            print("\nExiting.")
            break